### ISSUE TITLE
it will throw exception in my androd phone

### ISSUE THREAD

**Issue by yurili8** [vaadin/touchkit#427]
Caused by: com.vaadin.event.ListenerMethod$MethodException: Invocation of method modifyBootstrapPage in org.vaadin.touchkit.settings.TouchKitSettings failed.
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:519)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:273)
	at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:237)
	at com.vaadin.server.VaadinSession.modifyBootstrapResponse(VaadinSession.java:882)
	at com.vaadin.server.BootstrapHandler.getBootstrapHtml(BootstrapHandler.java:461)
	at com.vaadin.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:429)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1601)
	... 45 more
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 10: deferredjs\F8B727D236F0B241566A8E7ACADF6D8D\1.cache.js
	at java.net.URI.create(URI.java:852)
	at java.net.URI.resolve(URI.java:1036)
	at org.vaadin.touchkit.settings.TouchKitSettings.modifyBootstrapPage(TouchKitSettings.java:266)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:499)
	... 52 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 10: deferredjs\F8B727D236F0B241566A8E7ACADF6D8D\1.cache.js
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)

**Comment by TatuLund** [comment]
Fixed in version 4.2.1
